---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/replicas":
    get:
      summary: Retrieves all replicas
      tags:
      - Replicas
      responses:
        '200':
          description: replica found
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    reference:
                      type: string
                    category:
                      type: string
                    price:
                      type: number
            application/xml:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    reference:
                      type: string
                    category:
                      type: string
                    price:
                      type: number
        '404':
          description: replica not found
        '406':
          description: unsupported accept header
    post:
      summary: Creates a replica
      tags:
      - Replicas
      parameters: []
      responses:
        '201':
          description: replica created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
              required:
              - title
              - content
  "/replicas/{id}":
    get:
      summary: Retrieves a replica
      tags:
      - Replicas
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: replica found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  reference:
                    type: string
                  category:
                    type: string
                  price:
                    type: number
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  reference:
                    type: string
                  category:
                    type: string
                  price:
                    type: number
        '404':
          description: replica not found
        '406':
          description: unsupported accept header
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
